name: packer

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'      
jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    env: 
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
      FOLDER_ID: ${{ secrets.FOLDER_ID }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}           
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.4" # or `latest`          

      - name: Run `packer validate`
        id: validate
        run:  "packer validate ./yc-custom.pkr.hcl"      
        
      - name: Run `packer build`
        id: build
        run: "packer build ./yc-custom.pkr.hcl"   
